name: Murawski Design
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39177
title: Murawski Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9a9aa'
    - '#e6e6e7'
    - '#1a3668'
    - '#326297'
    - '#646d88'
  brandStrength: 0.6902844253927469
  lightness: 0.7220769834239036
  saturation: 0.22769146459177136
  rhythmicContrast: 0.20400798693299294
purpose: []
